services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb
    restart: unless-stopped
    ports:
        - "8086:8086"
    volumes:
        - influxdb:/var/lib/influxdb
    environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=admin
        - DOCKER_INFLUXDB_INIT_PASSWORD=my-s0ecret-password
        - DOCKER_INFLUXDB_INIT_ORG=fil-A3-back-bigData
        - DOCKER_INFLUXDB_INIT_BUCKET=animal-tracking
        - DOCKER_INFLUXDB_INIT_RETENTION=0d
        - DOCKER_INFLUXDB_INIT_DB=animal-tracking
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin-token
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
  notebook:
    image: grosinosky/bigdata_fila3_jupyter
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: yes
    command: start-notebook.py --NotebookApp.token=''    
  
volumes:
  influxdb: