services:
  influxdb2:
    image: influxdb:2
  notebook:
    image: grosinosky/bigdata_fila3_jupyter
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: yes
    command: start-notebook.py --NotebookApp.token=''    
  